name: ColorSnap
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    macOS: '14.0'
  xcodeVersion: '15.0'
  createIntermediateGroups: true

packages:
  KeyboardShortcuts:
    url: https://github.com/sindresorhus/KeyboardShortcuts
    from: '2.4.0'

settings:
  base:
    SWIFT_VERSION: '5.0'
    MARKETING_VERSION: '0.0.5'
    CURRENT_PROJECT_VERSION: '1'

targets:
  ColorSnap:
    type: application
    platform: macOS
    sources:
      - path: ColorSnap
        excludes:
          - '**/.DS_Store'
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.ColorSnap
        INFOPLIST_FILE: ColorSnap/Info.plist
        CODE_SIGN_ENTITLEMENTS: ColorSnap/ColorSnap.entitlements
        CODE_SIGN_STYLE: Automatic
        PRODUCT_NAME: ColorSnap
        COMBINE_HIDPI_IMAGES: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_HARDENED_RUNTIME: YES
        GENERATE_INFOPLIST_FILE: NO
    dependencies:
      - package: KeyboardShortcuts
