name: MacAppTemplate
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "5.0"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"

targets:
  MacAppTemplate:
    type: application
    platform: macOS
    sources:
      - path: MacAppTemplate
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.MacAppTemplate
        INFOPLIST_FILE: MacAppTemplate/Info.plist
        CODE_SIGN_ENTITLEMENTS: MacAppTemplate/MacAppTemplate.entitlements
        CODE_SIGN_STYLE: Automatic
        PRODUCT_NAME: MacAppTemplate
        COMBINE_HIDPI_IMAGES: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_HARDENED_RUNTIME: YES
        GENERATE_INFOPLIST_FILE: NO
